In [2]:
import numpy as np 
import matplotlib.pyplot as plt

In [3]:
state = np.load("../data/device_1.npz")
print(state.files)
events = state["event_counts"]

print(events)

['ID', 'acceptor_coordinates', 'donor_coordinates', 'electrode_coordinates', 'event_counts', 'device_time']
[[     0 100000      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 ...
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]]
